workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - test
  - build

test-job:
  stage: test
  image: node:20
  script:
    - npm i
    - npm run test
    - npm run check

build-job:
  stage: build
  image: node:20
  script:
    - npm i
    - npm run build
